# CLAUDE.md

This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository.

## Project Overview

GearWorkbench is a comprehensive FreeCAD workbench for designing all types of parametric gears optimized for 3D printing. Currently implements involute spur gears with plans to add helical, rack, bevel, and other gear types from the STLGears.com specification.

**Important**: The internal Python class is named `GearWorkbenchWB` (not `GearWorkbench`) to avoid conflict with the existing freecad.gears module which uses the same class name. The user-facing name is still "GearWorkbench".

**Key Components:**
- **InitGui.py**: FreeCAD workbench initialization and GUI integration
- **spurGear.py**: Main command (`SpurGearCreateObject`) and FeaturePython class (`SpurGear`)
- **gearMath.py**: Core involute mathematics, validation, and part generation
- **util.py**: General-purpose utility functions (coordinate conversion, sketcher helpers, validation)

## Development Environment

### Prerequisites
- Python 3.9+
- FreeCAD v1.0 or higher
- Development tools: pytest, black, flake8, pylint, mypy

### Installation for Development
```bash
# Install to FreeCAD Mod directory
cd ~/.local/share/FreeCAD/v1-1/Mod  # Adjust for your FreeCAD version
git clone https://github.com/iplayfast/GearWorkbench.git

# Install dev dependencies
cd GearWorkbench
pip install -r requirements-dev.txt
```

### Testing
```bash
# Run all tests (must be run within FreeCAD Python environment)
pytest tests/ -v

# Run with coverage
pytest tests/ --cov=. --cov-report=html

# Run specific test file
pytest tests/test_gearMath.py -v
```

### Code Quality
```bash
# Format code (line length: 127)
black gearMath.py spurGear.py InitGui.py

# Lint
flake8 .
pylint gearMath.py spurGear.py

# Type check
mypy gearMath.py --ignore-missing-imports
```

## Architecture

### FreeCAD Workbench Structure

The workbench follows FreeCAD's FeaturePython pattern (same as CycloidGearBox):

1. **GearWorkbenchWB** (InitGui.py): Registers workbench with FreeCAD (class name different from display name to avoid conflict)
2. **SpurGearCreateObject** (spurGear.py): Command that creates the gear object
3. **SpurGear** (spurGear.py): FeaturePython proxy holding parametric properties
4. **ViewProviderSpurGear** (spurGear.py): View provider for display and context menu

### Parameter Management

The `SpurGear` class stores all parameters as FreeCAD properties organized into groups:

**SpurGear Group** (main parameters):
- Module: Tooth size
- NumberOfTeeth: Count of teeth
- PressureAngle: Tooth profile angle (normally 20°)
- ProfileShift: Cutter offset (-1 to +1)
- Height: Gear thickness

**Bore Group** (center hole):
- BoreType: Enumeration (none/circular/square/hexagonal/keyway)
- BoreDiameter: Hole size
- SquareCornerRadius, HexCornerRadius: Rounding
- KeywayWidth, KeywayDepth: DIN 6885 keyway dimensions

**Read-Only Group** (calculated):
- PitchDiameter: Where gears mesh (module × teeth)
- BaseDiameter: Involute base circle
- OuterDiameter: Tooth tip diameter
- RootDiameter: Tooth root diameter

### Part Generation Flow

```
SpurGearCreateObject.Activated()
    → Creates spur_gear Body
    → Creates SpurGearParameters FeaturePython object
    → SpurGear.__init__()
        → Adds all properties with defaults from generate_default_parameters()
        → Sets up onChanged() handler

When properties change:
    → SpurGear.onChanged()
        → Marks Dirty = True
        → Updates calculated read-only properties
    → SpurGear.execute() triggers after 50ms (QTimer)
    → SpurGear.recompute()
        → Calls validate_spur_parameters()
        → Calls generate_spur_gear_part()
        → Regenerates 3D geometry

generate_spur_gear_part() workflow:
    1. Validate parameters
    2. Get or create 'spur_gear' Body
    3. Generate tooth profile via generate_tooth_profile()
    4. Create sketch with one tooth
    5. Pad tooth to height
    6. Polar pattern for all teeth
    7. Add bore if specified
    8. Recompute document
```

## Involute Mathematics

### Core Equations

The involute curve is the fundamental shape of gear teeth, generated by unwrapping a string from a circle.

#### Involute Function
```python
inv(α) = tan(α) - α  # In radians
```

Used to relate pressure angles at different radii.

#### Involute Point
Given a base radius and roll angle θ:
```python
x = rb × (cos(θ) + θ × sin(θ))
y = rb × (sin(θ) - θ × cos(θ))
```

#### Key Diameter Formulas

```python
# Pitch diameter (where gears mesh)
d = m × z  # module × teeth

# Base diameter (involute origin)
db = d × cos(α)  # α = pressure angle

# Addendum diameter (tooth tip)
da = d + 2m(1 + x)  # x = profile shift

# Dedendum diameter (tooth root)
df = d - 2m(1.25 - x)  # 1.25 = dedendum factor

# Tooth thickness at pitch circle
s = m(π/2 + 2x·tan(α))
```

### Tooth Profile Generation

The `generateToothProfile()` function creates one complete tooth using actual involute mathematics:

1. **Calculate dimensions**: Pitch, base, addendum, dedendum diameters and tooth thickness
2. **Right involute**: Generate 15 points from base/dedendum to addendum
   - Calculate roll angle range: θ = √((r/r_base)² - 1)
   - Use `involutePoint(base_radius, theta)` to generate each point
   - Rotate points by: `half_tooth_angle + involuteFunction(pressure_angle)` to center tooth
3. **Tip land**: Add 5 arc points at addendum radius connecting right to left side
4. **Left involute**: Generate 15 points (mirrored from right)
   - Same involute curve, rotated by negative angle for left side
5. **Root land**: Add 5 arc points at dedendum radius to close the profile
6. **Add to sketch**: Use `util.addPolygonToSketch()` to create connected line segments

**Key Implementation Details**:
- Uses line segments (polygon) rather than constraints for robustness
- Actual involute points calculated via `involutePoint(base_radius, theta)`
- Rotation accounts for both tooth centering and involute geometry
- Total ~39 points per tooth (15 + 5 + 15 + 5 points)

### Profile Shifting

Profile shifting moves the gear cutter radially during cutting:

- **Positive shift** (+): Moves cutter away, makes teeth thicker, prevents undercutting
- **Negative shift** (-): Moves cutter closer, makes teeth thinner
- **Zero shift** (0): Standard configuration

**Minimum Teeth Without Undercutting**:
```python
z_min = 2·ha* / sin²(α) - 2x
```
Where ha* = 1.0 (addendum factor), α = pressure angle, x = profile shift

At 20° pressure angle: z_min ≈ 17 teeth (without shift)

### Undercut Detection

`check_undercut()` validates:
1. Calculates minimum teeth for given pressure angle and shift
2. Compares actual teeth count
3. Returns (has_undercut: bool, min_teeth: float)

Triggers warning in console if undercutting detected.

## Key Functions Reference

### Involute Mathematics (gearMath.py)

- **`involute_function(angle)`**: Calculate inv(α) = tan(α) - α
- **`involute_point(base_radius, theta)`**: Point on involute curve at roll angle θ
- **`calc_pitch_diameter(module, num_teeth)`**: d = m × z
- **`calc_base_diameter(pitch_dia, pressure_angle_deg)`**: db = d × cos(α)
- **`calc_addendum_diameter(...)`**: Tooth tip diameter with profile shift
- **`calc_dedendum_diameter(...)`**: Tooth root diameter with profile shift
- **`calc_base_tooth_thickness(...)`**: Tooth width at pitch circle
- **`check_undercut(teeth, pressure_angle, shift)`**: Validate minimum teeth

### Validation (gearMath.py)

- **`validate_spur_parameters(parameters)`**: Comprehensive validation
  - Raises `GearParameterError` for invalid values
  - Checks ranges: module (0.3-75mm), teeth (6-150), pressure angle (1-35°)
  - Validates profile shift (-1 to +1)
  - Warns about undercutting

### Geometry Generation (gearMath.py)

- **`generate_tooth_profile(parameters)`**: Create one tooth outline
  - Returns list of FreeCAD Vectors
  - Includes involute curves, tip land, root fillet

- **`generate_spur_gear_part(doc, parameters)`**: Complete gear generation
  - Creates PartDesign::Body
  - Generates tooth sketch
  - Pads and patterns
  - Adds bore

- **`generate_bore(body, parameters, height)`**: Dispatch bore generation
  - Calls appropriate bore function based on type

- **`generate_circular_bore(...)`, `generate_square_bore(...)`, etc.**:
  - Create specific bore geometries
  - Use sketches and pockets

### Sketching Helpers (gearMath.py)

Same pattern as CycloidGearBox:
- **`newSketch(body, name)`**: Create sketch attached to body
- **`newPad(body, sketch, height, name)`**: Extrude sketch
- **`newPocket(body, sketch, height, name)`**: Cut sketch
- **`newPolar(body, feature, sketch, count, name)`**: Create polar array

### Utility Functions (util.py)

General-purpose functions extracted from CycloidGearBox for reuse across all gear types:

**Constants**:
- `DEG_TO_RAD`, `RAD_TO_DEG`: Angle conversion
- `MIN_TOOTH_COUNT`, `MAX_TOOTH_COUNT`: Validation limits

**Coordinate Conversion**:
- **`toPolar(x, y)`**: Convert Cartesian to (radius, angle_radians)
- **`toCart(r, a)`**: Convert polar to (x, y)
- **`rotatePoint(x, y, angle_rad)`**: Rotate point around origin

**Math Utilities**:
- **`clamp1(a)`**: Clamp value to [-1, 1]
- **`clamp(value, min_val, max_val)`**: Clamp to range
- **`involuteFunction(angle)`**: Calculate inv(α) = tan(α) - α
- **`involutePoint(base_radius, theta)`**: Point on involute curve

**Vector Utilities**:
- **`fcVec(x)`**: Convert list to FreeCAD Vector
- **`vectorDistance(v1, v2)`**: Distance between vectors

**BSpline/Curve**:
- **`makeBspline(pts)`**: Create BSpline curves from point lists
- **`makeBsplineWire(pts)`**: Create BSpline wire

**Sketcher Helpers**:
- **`createSketch(body, name)`**: Create sketch in body
- **`createPad(body, sketch, height, name)`**: Create pad feature
- **`createPolar(body, pad, sketch, count, name)`**: Create polar pattern
- **`createPocket(body, sketch, height, name)`**: Create pocket
- **`sketchCircle(sketch, x, y, diameter, last, Name, ref)`**: Add constrained circle
- **`sketchCircleOfCircles(...)`**: Add circular pattern of circles
- **`parametricCircle(radius, count, index)`**: Calculate position in circular pattern
- **`addPolygonToSketch(sketch, points, closed)`**: Add polygon (line segments) to sketch
- **`addBSplineToSketch(sketch, points, periodic)`**: Add BSpline curve to sketch

**Part Management**:
- **`readyPart(doc, name)`**: Create or clean a body

**Validation**:
- **`validateToothCount(toothCount, min, max)`**: Validate tooth range
- **`validatePositive(value, name)`**: Ensure positive value
- **`validateRange(value, name, min_val, max_val)`**: Validate range

**Exceptions**:
- **`ParameterValidationError`**: Base exception for parameter validation

## Important Constraints

### Parameter Interdependencies

1. **Module range**: 0.3mm (very small) to 75mm (very large)
2. **Teeth range**: 6 (with profile shift) to 150
3. **Pressure angle**: 1° to 35° (20° standard)
4. **Profile shift**: -1 to +1
5. **Undercut limit**: Teeth ≥ z_min for given pressure angle

### Meshing Requirements

For two gears to mesh properly:
- **Same module**: Both gears must have identical module
- **Same pressure angle**: Both must use same pressure angle
- **Center distance**: C = (z1 + z2) × m / 2
- **Gear ratio**: ratio = z2 / z1

### Typical Parameter Ranges

| Parameter | Min | Max | Typical 3D Printing |
|-----------|-----|-----|---------------------|
| Module | 0.3mm | 75mm | 1.5-3mm |
| Teeth | 6 | 150 | 12-60 |
| Pressure Angle | 1° | 35° | 20° |
| Profile Shift | -1 | +1 | 0 to +0.5 |
| Height | 0.01mm | 400mm | 5-20mm |

## Coding Standards

### Style Guide (from spurGear.py header)

```python
def functions_are_lowercase(variables_as_well):
    pass

class ClassesArePascalCase:
    pass

SomeClass.some_variable = value
```

### Documentation

- Use Google-style docstrings with type hints
- Document Args, Returns, Raises
- Maximum line length: 127 characters
- PEP 8 compliance

### Testing

- Place tests in `tests/` directory
- Use pytest fixtures for setup
- Aim for >80% coverage
- Test both valid and invalid parameter ranges
- Test known ISO gear examples

## Common Development Tasks

### Adding a New Parameter

1. Add property in `SpurGear.__init__()` with appropriate group
2. Add to `GetParameters()` dictionary conversion
3. Add validation in `validate_spur_parameters()` if needed
4. Update `generate_spur_gear_part()` or related functions
5. Add tests for new parameter
6. Update default in `generate_default_parameters()`
7. Document in README.md

### Adding a New Bore Type

1. Add option to BoreType enumeration in `SpurGear.__init__()`
2. Add required parameters as properties (e.g., dimensions)
3. Create `generate_xxx_bore()` function in gearMath.py
4. Add case to `generate_bore()` dispatcher
5. Add tests
6. Update documentation

### Modifying Tooth Profile

1. Edit `generate_tooth_profile()` in gearMath.py
2. Key areas:
   - Involute point generation (lines ~467-481)
   - Rotation angle calculation (accounts for tooth thickness and involute function)
   - Tip land geometry
   - Root fillet (currently simplified)
3. Test with various module and teeth combinations
4. Verify no self-intersection or invalid geometry
5. Check meshing with mating gear

### Adding New Gear Types (Future)

Example: Helical gear
1. Create `helicalGear.py` similar to `spurGear.py`
2. Add HelixAngle property
3. Extend `generate_tooth_profile()` with helix twist
4. Use loft or sweep instead of simple pad
5. Register command in `InitGui.py`
6. Add icon
7. Add tests

## Troubleshooting

### "GearParameterError: Number of teeth must be >= 6"
- Increase NumberOfTeeth to at least 6

### "May have undercutting!" warning
- Increase NumberOfTeeth (≥17 for 20° PA)
- Or use positive ProfileShift (try +0.3 to +0.5)
- Or reduce PressureAngle (less common)

### Teeth look wrong or intersect
- Check Module is appropriate for gear size
- Verify PressureAngle is reasonable (15-25°)
- Check ProfileShift isn't too extreme
- Ensure NumberOfTeeth is sufficient

### Gears don't mesh
- Verify both gears have identical Module
- Verify both have identical PressureAngle
- Calculate correct center distance: (teeth1 + teeth2) × module / 2
- Check for clearance (small gap between teeth)

### Polar pattern fails
- Check tooth profile doesn't self-intersect
- Verify sketch is valid before padding
- Ensure polar pattern count matches NumberOfTeeth

## Performance Considerations

- **Involute points**: 15 points per tooth side (30 total per tooth)
  - More points = smoother curve but slower generation
  - Fewer points = faster but faceted

- **Recompute delay**: 50ms QTimer prevents excessive regeneration

- **Parameter updates**: Only recomputes when Dirty flag is set

## References

### Gear Theory
- Dudley's Handbook of Practical Gear Design
- ISO 53:1998 - Cylindrical gears for general engineering
- ANSI/AGMA 1012-F90 - Gear Nomenclature
- DIN 6885 - Parallel keys and keyways

### Involute Mathematics
- [Wikipedia: Involute](https://en.wikipedia.org/wiki/Involute)
- [Wikipedia: Involute Gear](https://en.wikipedia.org/wiki/Involute_gear)
- [STLGears Theory Pages](https://www.stlgears.com/theory)

### Implementation References
- FreeCAD FeaturePython documentation
- CycloidGearBox workbench (similar architecture)

## Future Expansion Path

When adding new gear types (following user request), consider:

1. **Helical Gears**: Add helix angle, modify tooth generation for twist
2. **Rack**: Linear gear, modify involute for infinite radius
3. **Internal Gears**: Inverted involute (convex → concave)
4. **Bevel Gears**: Conical geometry, different math
5. **Herringbone**: Two helical sections, opposite hand

Each new type should:
- Follow same FeaturePython pattern
- Reuse math functions where possible
- Have separate command and icon
- Include comprehensive tests
- Document in README and CLAUDE.md
